### ISSUE TITLE
not compat with some old nbs files

### ISSUE THREAD

**Issue by lgc2333** [Encode42/NBS.js#5]
see https://github.com/TheInfamousAlk/nbs/blob/master/Bad%20Apple.nbs

**Comment by encode42** [comment]
Please include more information in your report. How isn't it compatible? What errors are thrown? etc.

**Comment by lgc2333** [comment]
![Screenshot_20220818-021646](https://user-images.githubusercontent.com/59048777/185291823-c80b2cdb-28ca-43cf-b24d-deb20fa755ff.png)
errors are in the chat messages

**Comment by lgc2333** [comment]
[code here](https://github.com/lgc2333/LLSEPlugins/blob/main/NbsPlayer/src/index.ts#L132)

**Comment by encode42** [comment]
Fixed in d184af6d5f6012ca689cf084b7d5ff44dc789c00 / [`v4.0.0`](https://www.npmjs.com/package/@encode42/nbs.js/v/4.0.0).

Turns out that the song's `nbsVersion` was not being set to `0` for songs that use the v0 format. Easy fix!
